In [1]:
import pandas as pd

In [ ]:
#df=pd.read_csv('../ArquivosExternos/dados_tratados_v2/dc_Softskills_tratado.csv', encoding='utf-8')

In [ ]:
import os

# variável de ambiente para construir o caminho
caminho_base = os.environ.get("CAMINHO_ARQUIVOS_CSV")
caminho_completo = os.path.join(caminho_base, "dados_tratados_v2", "dc_Softskills_tratado.csv")

df = pd.read_csv(caminho_completo)

In [3]:
df.head()

   ID              Soft Skills
0   1       Foco em resultados
1   1              Resiliência
2   1  Capacidade de liderança
3   1     Aprendizado contínuo
4   1              Colaboração

In [ ]:
df.rename(columns={'Soft Skills' : 'Soft_Skills'}, inplace=True)

In [ ]:
import sys
# Adiciona o diretório-raiz do projeto ao sys.path
sys.path.append('/app')


import importlib
import utils.modelagem_utils
importlib.reload(utils.modelagem_utils)   # recarrega o módulo com as mudanças

from utils.modelagem_utils import criar_tabelas_dimensao_e_fato

# 2. Chama a função para criar as tabelas
dim_softskills, fato_softskills = criar_tabelas_dimensao_e_fato(
    df=df,
    nome_coluna_dimensao='Soft_Skills',
    nome_coluna_id_fato='idColaborador',
    nome_tabela_dimensao='dim_Softskills',
    nome_tabela_fato='fato_Softskills',
)

In [6]:
print("Tabelas criadas usando a função genérica:")
print("Dimensão (head):")
dim_softskills.head()

Tabelas criadas usando a função genérica:
Dimensão (head):

   idSoft_Skills              Soft_Skills
0              1       Foco em resultados
1              2              Resiliência
2              3  Capacidade de liderança
3              4     Aprendizado contínuo
4              5              Colaboração

In [7]:
print("\nFato (head):")
fato_softskills.head()

Fato (head):

   idColaborador  idSoft_Skills
0              1              1
1              1              2
2              1              3
3              1              4
4              1              5