In [1]:
import pandas as pd
import os

In [ ]:
# Carrega os dados dos arquivos CSV
# df_primarios = pd.read_csv('../ArquivosExternos/dados_tratados_v2/dc_DadosPrimarios_Tratado.csv')
# df_admissao = pd.read_csv('../ArquivosExternos/dados_tratados_v2/dc_DataAdmissao_Tratado.csv')

In [ ]:

# variável de ambiente para construir o caminho
caminho_base = os.environ.get("CAMINHO_ARQUIVOS_CSV")
caminho_completo = os.path.join(caminho_base, "dados_tratados_v2", "dc_DadosPrimarios_Tratado.csv")

df_primarios = pd.read_csv(caminho_completo)

In [ ]:

# variável de ambiente para construir o caminho
caminho_base = os.environ.get("CAMINHO_ARQUIVOS_CSV")
caminho_completo = os.path.join(caminho_base, "dados_tratados_v2", "dc_DataAdmissao_Tratado.csv")

df_admissao = pd.read_csv(caminho_completo)

In [ ]:
# Renomeia as colunas para melhor clareza
df_admissao.rename(columns={'Id': 'idColaborador', 'Data': 'Data_Admissao'}, inplace=True)

In [4]:
# Converte a coluna 'Data_Admissao' para o formato de data e hora
df_admissao['Data_Admissao'] = pd.to_datetime(df_admissao['Data_Admissao'])

In [5]:

# --- Etapa 1: Criar a Tabela de Dimensão de Data de Admissão ---

# Pega as datas de admissão únicas
dim_data_admissao = pd.DataFrame(df_admissao['Data_Admissao'].unique(), columns=['Data_Admissao'])
# Atribui um ID único a cada data, começando em 1
dim_data_admissao.insert(0, 'idData_Admissao', range(1, 1 + len(dim_data_admissao)))

In [ ]:
# --- Etapa 2: Modificar a Tabela de Colaboradores para ter a chave da data ---

# Faz um 'merge' da tabela de admissão com a tabela de dimensão de datas para adicionar o 'idData_Admissao'
df_admissao = df_admissao.merge(dim_data_admissao, on='Data_Admissao', how='left')

# faz um 'merge' da tabela de dados primários com a tabela de admissão
dim_colaborador = df_primarios.merge(df_admissao[['idColaborador', 'idData_Admissao']], on='idColaborador', how='left')

In [7]:
# Exibe as primeiras linhas das tabelas criadas para verificação
print("Tabela de Dimensão de Data de Admissão (dim_data_admissao):")
dim_data_admissao.head()

Tabela de Dimensão de Data de Admissão (dim_data_admissao):

   idData_Admissao Data_Admissao
0                1    2002-03-01
1                2    2002-06-15
2                3    2002-09-22
3                4    2002-12-05
4                5    2003-03-18

In [8]:
print("\nTabela de Colaboradores (dim_colaborador):")
dim_colaborador.head()

Tabela de Colaboradores (dim_colaborador):

,idColaborador,Nome,Email,CPF,Data de Nascimento,Telefone,Estado,Endereço,Telefone_status,Situacao_CPF,idCidade,idData_Admissao
0,7,Vanessa Nogueira,vanessa.nogueira@exemplo.com,345.123.678-90,1992-09-05,+55 (21) 9876-1234,RJ,"Rua Mato Grosso, 192",Inválido: celular com tamanho incorreto,Válido,1,7
1,8,Eduardo Araújo,edu.araújo@empresa.com,024.878.550-22,1980-07-30,+55 (11) 93220-4567,SP,"Rua Rio Branco, 831",Válido,Válido,2,8
2,9,Mariana Silva,mariana@dominio.com.br,123.456.789-00,1999-06-15,+55 (19) 99765-3332,SP,"Rua Horizonte Azul, 779",Válido,Válido,3,9
3,10,Rafael Costa,rafael.costa@email.com,789.654.321-00,1987-03-22,+55 (71) 91234-5678,BA,"Rua Cruzeiro do Sul, 162",Válido,Válido,4,10
4,11,Thiago Moura,thiago@dominio.com,123.456.789-00,1990-01-12,+55 (21) 99999-0001,RJ,"Rua do Sol, 121",Válido,Válido,1,11

In [ ]:
dim_data_admissao['idData_Admissao'] = dim_data_admissao['idData_Admissao'].astype(int)

In [ ]:
# Salva as novas tabelas em arquivos CSV
# dim_data_admissao.to_csv('../ArquivosExternos/dados_tratados_v2/dc_DataAdmissao_Tratado.csv', index=False)
# dim_colaborador.to_csv('../ArquivosExternos/dados_tratados_v2/dc_DadosPrimarios_tratado.csv', index=False)

In [ ]:

# variável de ambiente para construir o caminho
caminho_base_arquivos = os.environ.get("CAMINHO_ARQUIVOS_CSV")
caminho_saida = os.path.join(caminho_base_arquivos, "dados_tratados_v2", "dc_DataAdmissao_Tratado.csv")

# variável caminho_saida
dim_data_admissao.to_csv(caminho_saida, index=False)

In [ ]:

# variável de ambiente para construir o caminho
caminho_base_arquivos = os.environ.get("CAMINHO_ARQUIVOS_CSV")
caminho_saida = os.path.join(caminho_base_arquivos, "dados_tratados_v2", "dc_DadosPrimarios_tratado.csv")

# variável caminho_saida
dim_colaborador.to_csv(caminho_saida, index=False)