In [1]:
import pandas as pd
import os

In [ ]:
# variável de ambiente para construir o caminho
caminho_base = os.environ.get("CAMINHO_ARQUIVOS_CSV")
caminho_completo = os.path.join(caminho_base, "dados_brutos", "dados_colaboradores 1(SoftSkills).csv")

df_soft_skills = pd.read_csv(caminho_completo)

In [3]:
# Visualizar as primeiras linhas
df_soft_skills.head(10)

,ID,Soft Skill 1,Soft Skill 2,Soft Skill 3,Soft Skill 4,Soft Skill 5
0,1,Foco em resultados,Resiliência,Aprendizado contínuo,Colaboração,Capacidade de liderança
1,2,Proatividade,Colaboração,Visão sistêmica,Aprendizado contínuo,Trabalho interdisciplinar
2,3,Autonomia,Resiliência,Curiosidade,Gestão de prioridades,Responsabilidade
3,4,Negociação,Gestão de prioridades,Capacidade de liderança,NaN,NaN
4,5,Pensamento analítico,Adaptabilidade,Proatividade,Aprendizado contínuo,NaN
5,6,Trabalho interdisciplinar,Pensamento analítico,Gestão de prioridades,NaN,NaN
6,7,Responsabilidade,Negociação,NaN,NaN,NaN
7,8,Gestão do tempo,Resolução de problemas,Foco em resultados,Capacidade de liderança,Inteligência emocional
8,9,Gestão do tempo,Visão sistêmica,NaN,NaN,NaN
9,10,Habilidades de comunicação,Capacidade de liderança,Resiliência,NaN,NaN

In [6]:
print(df_soft_skills.columns)

Index(['ID', 'Soft Skill 1', 'Soft Skill 2', 'Soft Skill 3', 'Soft Skill 4',
       'Soft Skill 5'],
      dtype='object')

In [ ]:
df_soft_skills.rename(columns={'ID': 'idColaborador'}, inplace=True)

In [ ]:
df_soft_skills_trat = df_soft_skills.melt(
    id_vars='idColaborador',
    value_vars=['Soft Skill 1', 'Soft Skill 2', 'Soft Skill 3', 'Soft Skill 4',
       'Soft Skill 5'],
    value_name='Soft Skills'
)

In [ ]:
# Remover a coluna gerada com os nomes soft skills 1,2,3 ...
df_soft_skills_trat = df_soft_skills_trat[['idColaborador', 'Soft Skills']]

In [5]:
# Visualizar o resultado
display(df_soft_skills_trat.head(10))

   ID                 Soft Skills
0   1          Foco em resultados
1   2                Proatividade
2   3                   Autonomia
3   4                  Negociação
4   5        Pensamento analítico
5   6   Trabalho interdisciplinar
6   7            Responsabilidade
7   8             Gestão do tempo
8   9             Gestão do tempo
9  10  Habilidades de comunicação

In [ ]:
# Reordenar pelo ID
df_soft_skills_trat = df_soft_skills_trat.sort_values(by='idColaborador').reset_index(drop=True)
display (df_soft_skills_trat)

     ID              Soft Skills
0     1       Foco em resultados
1     1              Resiliência
2     1  Capacidade de liderança
3     1     Aprendizado contínuo
4     1              Colaboração
..   ..                      ...
395  80                      NaN
396  80   Dar e receber feedback
397  80                      NaN
398  80              Resiliência
399  80  Capacidade de liderança

[400 rows x 2 columns]

In [7]:
# Verificar presença de NaN (116 vazios)
df_soft_skills_trat.isnull().sum().sum()

np.int64(116)

In [ ]:
# Remover NaN (aqui é possível pois trata-se apenas de colaboradores que possuem menos de 5 softskills)
df_soft_skills_trat = df_soft_skills_trat.dropna(subset=['Soft Skills'])
display (df_soft_skills_trat)

     ID              Soft Skills
0     1       Foco em resultados
1     1              Resiliência
2     1  Capacidade de liderança
3     1     Aprendizado contínuo
4     1              Colaboração
..   ..                      ...
390  79           Adaptabilidade
391  79  Capacidade de liderança
396  80   Dar e receber feedback
398  80              Resiliência
399  80  Capacidade de liderança

[284 rows x 2 columns]

In [ ]:
# Contar as ocorrências de cada soft skill
contagem_soft_skills = df_soft_skills_trat['Soft Skills'].value_counts()

# Criar um df com a contagem
df_contagem = contagem_soft_skills.reset_index()
df_contagem.columns = ['Soft Skill', 'Frequência']

# Contar o número total de categorias únicas
total_categorias = df_contagem.shape[0]

display(df_contagem)
print(f"\nTotal de Soft Skills listadas: {total_categorias}")

                    Soft Skill  Frequência
0      Capacidade de liderança          21
1                 Criatividade          17
2    Trabalho interdisciplinar          16
3       Dar e receber feedback          15
4                      Empatia          15
5                   Negociação          14
6           Foco em resultados          13
7        Gestão de prioridades          13
8       Resolução de problemas          13
9                  Resiliência          12
10                   Autonomia          12
11        Pensamento analítico          12
12        Aprendizado contínuo          11
13  Habilidades de comunicação          11
14                 Curiosidade          10
15                 Colaboração          10
16             Visão sistêmica           9
17          Ética profissional           9
18                Proatividade           8
19              Adaptabilidade           8
20      Inteligência emocional           8
21          Pensamento crítico           8
22             Gestão do tempo           7
23        Atenção aos detalhes           7
24            Responsabilidade           5

Total de soft skills listadas: 25

In [ ]:
#df_soft_skills_trat.to_csv("../ArquivosExternos/dados_tratados_v2/dc_Softskills_tratado.csv", index=False, encoding='utf-8')

In [ ]:

# variável de ambiente para construir o caminho
caminho_base_arquivos = os.environ.get("CAMINHO_ARQUIVOS_CSV")
caminho_saida = os.path.join(caminho_base_arquivos, "dados_tratados_v2", "dc_Softskills_tratado.csv")

# variável caminho_saida
df_soft_skills_trat.to_csv(caminho_saida, index=False)